name: ticketapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.5
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tick.png
    - assets/images/back.png
    - assets/images/content.png
    - assets/images/bar.png
    - assets/images/user.png
    - assets/images/search.png
   
